# Generated by Django 3.1.7 on 2022-02-05 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LLINS_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nets',
            name='month',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nets',
            name='year',
            field=models.IntegerField(default=2020, verbose_name=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nets',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
