# Generated by Django 3.1.7 on 2022-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLINS_API', '0002_auto_20220205_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsdata',
            options={},
        ),
        migrations.AlterField(
            model_name='nets',
            name='year',
            field=models.IntegerField(),
        ),
    ]
