# Generated by Django 4.0.2 on 2022-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLINS_API', '0003_auto_20220205_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('Month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2)),
                ('County', models.CharField(choices=[('kisumu', 'Kisumu'), ('vihiga', 'Vihiga'), ('busia', 'Busia')], default='Kisumu', max_length=30)),
                ('SubCounty', models.CharField(choices=[('kisumu west', 'Kisumu West'), ('kisumu central', 'Kisumu Central'), ('kisumu east', 'Kisumu East'), ('seme', 'Seme'), ('muhoroni', 'Muhoroni'), ('nyando', 'Nyando'), ('nyakach', 'Nyakach'), ('sabatia', 'Sabatia,'), ('vihiga', 'vihiga'), ('luanda', 'Luanda'), ('emuhaya', 'Emuhaya'), ('hamisi', 'Hamisi'), ('teso north', 'Teso North'), ('teso south', 'Teso South'), ('nambale', 'Nambale'), ('matayos', 'Matayos'), ('butula', 'Butula'), ('samia', 'Samia'), ('bunyala', 'Bunyala')], default='muhoroni', max_length=30)),
                ('netsProvided', models.IntegerField()),
                ('netsIssued', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('Month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2)),
                ('County', models.CharField(choices=[('kisumu', 'Kisumu'), ('vihiga', 'Vihiga'), ('busia', 'Busia')], default='Kisumu', max_length=30)),
                ('SubCounty', models.CharField(choices=[('kisumu west', 'Kisumu West'), ('kisumu central', 'Kisumu Central'), ('kisumu east', 'Kisumu East'), ('seme', 'Seme'), ('muhoroni', 'Muhoroni'), ('nyando', 'Nyando'), ('nyakach', 'Nyakach'), ('sabatia', 'Sabatia,'), ('vihiga', 'vihiga'), ('luanda', 'Luanda'), ('emuhaya', 'Emuhaya'), ('hamisi', 'Hamisi'), ('teso north', 'Teso North'), ('teso south', 'Teso South'), ('nambale', 'Nambale'), ('matayos', 'Matayos'), ('butula', 'Butula'), ('samia', 'Samia'), ('bunyala', 'Bunyala')], default='muhoroni', max_length=30)),
                ('PatientsReceived', models.IntegerField()),
                ('PatientsNets', models.IntegerField()),
                ('PatientswithoutNets', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Nets',
        ),
        migrations.DeleteModel(
            name='PatientsData',
        ),
    ]
